### PR TITLE
v1 Scales

### PR DESCRIPTION
**Pull request by youshy**
Took me a second longer than I've anticipated (life, huh?), but here I am!

I've redesigned the model slightly, I think it accommodates the scales a bit better now. Scales are divided into four groups - derived from Ionian, Melodic Minor, Harmonic Minor, and non-modal scales.

Happy to help with more stuff!

### CODE REVIEW

**Comment by mattetti** [comment]
OMg i'm so sorry, I missed the PR and just noticed it now that you closed it

**Comment by youshy** [comment]
No worries mate! I want to redo it either way to clean it up - theres a lot of things I've learned since I've opened this one!

**Comment by youshy** [comment]
@mattetti I'll clean up the tests for this PR and, if that's ok, assign you when done.

I'll have some free time on my hands next month and would like to learn more about how we can make the audio processing reality in Go - if you have anything in the pipeline that might require some work, let me know!

**Comment by mattetti** [comment]
Sounds good, thanks!

**Pull request closed without merging**
